name: tests
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 9 * * 3
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: mig4/setup-bats@v1
        with:
          bats-version: 1.6.0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: pip
      - run: pip install -r requirements.txt
      - run: bats -r .
